language: rust
sudo: false
 cache:
    directories:
     - _scraper/target
     - _tmp/

before_script:
  - cargo install --git https://github.com/cobalt-org/cobalt.rs
  - export PATH="$PATH:/home/travis/.cargo/bin"

script:
  - cd _scraper && cargo build --release
  - _scraper/target/release/scraper _data/crates.yaml
  - cobalt build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_DEPLOY_TOKEN
  local_dir: '_site'
  fqdn: www.arewelearningyet.com
  on:
    branch: master
