name: Publish

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '30 23 * * 0'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: ./.github/workflows/build.yml@v1

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _site
